### ISSUE TITLE
DOC: computing the gradient along the function.

### ISSUE THREAD

**Issue by Dapid** [OptimoJoe/Optizelle#16]
Here is how: http://forum.optimojoe.com/t/computing-the-gradient-alongside-the-function/29

It should be added to the docs, I will work on an example.

**Comment by josyoun** [comment]
Fixed in commit 06b224616f2e579ad076d151dd0e91f83c461ae9.  Thanks for reporting this.

As a side note, although I've documented how to properly cache just about everything you ever want to cache, there's still some ongoing issues with effective caching.  With the current scheme, caching doesn't benefit from restarts since the cached information will be lost when the algorithm exists, unless the user does some more elaborate trickery.  In addition, Optizelle really should manage exactly when and where caching occurs since it's moderately algorithm dependent.  That being said, implementing a more sophisticated caching system will require adding additional types, and hence template parameters, for the cached information.  Basically, since this information varies depending on the underlying functions, we need to parameterize the code based on this information.  That's going to make things a little ugly for something that many users don't want to deal with.  As such, I want some time to clarify and clean up some ideas that I've been kicking around on how to manage this.
