### ISSUE TITLE
CCmake is picking up Python3

### ISSUE THREAD

**Issue by Dapid** [OptimoJoe/Optizelle#48]
CCmake by default picks Python3, and fails. It would be good if it were to choose the right one (perhaps from `which python2.7`, with the added bonus that it would pick up if I am on a virtualenv. No idea how to do this in Cmake, though.).

My OS is Fedora 22, GCC 5.1.1, (c)cmake 3.3.2. I have both Python 2.7 and 3.4 installed.

**Comment by josyoun** [comment]
Thanks for letting me know!  Fixed on commit `d63d1525427a3d00e526e3e76bbad62abea6d980`.  Note, this on the develop branch and not master.  Mostly because I really want to remerge develop into master soon and keep adding tags for bug fixes.  If need be, I can reopen and push the changes into master as well, but it should all be a wash in a few days.

**Comment by Dapid** [comment]
This works like a charm. It is indeed picking up my virtualenv.
